cashbook/urls.py
from django.urls import path
from . import views

app_name = "cashbook"
urlpatterns = [
    path("", views.index, name="index"),
    path('accounts/<str:acc_name>/', views.accounts_view, name='accounts_view'),

    path("transaction/cash_in", views.cash_in, name="cash_in"),
    path("transaction/cash_out", views.cash_out, name="cash_out"),
    path('transaction/edit/<int:transaction_id>/', views.edit_transaction, name='edit_transaction'),
    path('transaction/delete/', views.delete_transaction, name='delete_transaction'),
    
    path('contact/', views.contact_view, name='contact'),
    
    path('category/', views.manage_category, name='manage_category'),
    path('category/add', views.add_category, name='add_category'),
    path('category/edit/<int:category_id>', views.edit_category, name='edit_category'),
    path('category/delete/', views.delete_category, name='delete_category'),
]

cashmanager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("cashbook/", include("cashbook.urls"))
]

cashbook/models.py
from django.db import models
import datetime

class Category(models.Model):
    name = models.CharField(max_length=20)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name
    
class Account(models.Model):
    name            = models.CharField(max_length=20)
    initial_balance = models.FloatField(default=0)
    net_balance  = models.FloatField(default=0)
    last_updated = models.DateField(default=datetime.date.today)

    def __str__(self):
        return self.name

# define Transaction Type
class TrxType(models.Model):
    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name
    
class Transaction(models.Model):
    amount          = models.FloatField(blank=False, null=False)
    account_id      = models.ForeignKey(Account, on_delete=models.CASCADE)
    category_id     = models.ForeignKey(Category, null=True, on_delete=models.SET_NULL)
    trx_type_id     = models.ForeignKey(TrxType, on_delete=models.CASCADE)
    remarks         = models.TextField(blank=True)
    create_date     = models.DateTimeField("date created")

    def __str__(self):
        return f"Amount: {self.amount}, Remarks: {self.remarks}, Date: {self.create_date},"

cashbook/forms.py
# forms.py

from django import forms
from .models import Transaction, Category

class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ['amount', 'account_id', 'category_id', 'trx_type_id', 'remarks', 'create_date']

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']

cashbook/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .forms import TransactionForm, CategoryForm
from django.db.models import Q, Sum
from datetime import date, timedelta
from cashbook.models import Category, Account, Transaction, TrxType
from django.core.mail import send_mail
from django.conf import settings
import datetime
from dateutil import parser

def index(request):
    
    transactions = Transaction.objects.all()
    accounts = Account.objects.order_by("name")

    context = {
        'accounts'      : accounts,
        'transactions'  : transactions
    }
    return render(request, 'cashbook/accounts.html', context)

def accounts_view(request, acc_name):
    trx_types = TrxType.objects.all()
    categories = Category.objects.all()

    type_cash_in = TrxType.objects.get(name='cash_in')
    type_cash_out = TrxType.objects.get(name='cash_out')

    # Retrieve filter values
    date_filter = request.GET.get('date-filter')
    trx_type_filter = request.GET.get('trx-type')
    category_filter = request.GET.get('category')
    
    # Transaction by date
    trx_all = Transaction.objects.order_by("-create_date")
    trx_today = trx_all.filter(create_date__date=datetime.date.today())
    trx_yesterday = trx_all.filter(create_date__date=datetime.date.today() - datetime.timedelta(days=1))
    trx_this_month = trx_all.filter(create_date__month=datetime.date.today().month)
    trx_last_month = trx_all.filter(create_date__month=datetime.date.today().month - 1)

    # Calculate net balance, opening balance, total cash in, and total cash out
    acc_cash = Account.objects.get(name='cash')
    initial_balance = acc_cash.initial_balance
    opening_balance = 0
    total_cash_in = 0
    total_cash_out = 0
    net_balance = 0

    # Apply filters
    if date_filter:
        # Apply date filter based on the selected value
        
        if date_filter == 'today':
            # Filter transactions for today
            total_cash_in = trx_today.filter(trx_type_id=type_cash_in.id).aggregate(total_cash_in=Sum('amount'))['total_cash_in'] or 0
            total_cash_out = trx_today.filter(trx_type_id=type_cash_out.id).aggregate(total_cash_out=Sum('amount'))['total_cash_out'] or 0
            prev_total_cash_in = trx_all.filter(trx_type_id=type_cash_in.id, create_date__lt=datetime.date.today()).aggregate(prev_total_cash_in=Sum('amount'))['prev_total_cash_in'] or 0
            prev_total_cash_out = trx_all.filter(trx_type_id=type_cash_out.id, create_date__lt=datetime.date.today()).aggregate(prev_total_cash_out=Sum('amount'))['prev_total_cash_out'] or 0
            opening_balance = (initial_balance + prev_total_cash_in - prev_total_cash_out) or 0
            net_balance = (opening_balance + total_cash_in - total_cash_out) or 0
            transactions = trx_today
        elif date_filter == 'all-time':
            # Filter transactions for all-time
            total_cash_in = trx_all.filter(trx_type_id=type_cash_in.id).aggregate(total_cash_in=Sum('amount'))['total_cash_in'] or 0
            total_cash_out = trx_all.filter(trx_type_id=type_cash_out.id).aggregate(total_cash_out=Sum('amount'))['total_cash_out'] or 0
            opening_balance = initial_balance or 0
            net_balance = (opening_balance + total_cash_in - total_cash_out) or 0
            transactions = trx_all
        elif date_filter == 'yesterday':
            # Filter transactions for yesterday
            total_cash_in = trx_yesterday.filter(trx_type_id=type_cash_in.id).aggregate(total_cash_in=Sum('amount'))['total_cash_in'] or 0
            total_cash_out = trx_yesterday.filter(trx_type_id=type_cash_out.id).aggregate(total_cash_out=Sum('amount'))['total_cash_out'] or 0
            prev_total_cash_in = trx_all.filter(trx_type_id=type_cash_in.id, create_date__lt=datetime.date.today() - datetime.timedelta(days=1)).aggregate(prev_total_cash_in=Sum('amount'))['prev_total_cash_in'] or 0
            prev_total_cash_out = trx_all.filter(trx_type_id=type_cash_out.id, create_date__lt=datetime.date.today() - datetime.timedelta(days=1)).aggregate(prev_total_cash_out=Sum('amount'))['prev_total_cash_out'] or 0
            opening_balance = (initial_balance + prev_total_cash_in - prev_total_cash_out) or 0
            net_balance = (opening_balance + total_cash_in - total_cash_out) or 0
            transactions = trx_yesterday
        elif date_filter == 'this_month':
            # Filter transactions for the current month
            total_cash_in = trx_this_month.filter(trx_type_id=type_cash_in.id).aggregate(total_cash_in=Sum('amount'))['total_cash_in'] or 0
            total_cash_out = trx_this_month.filter(trx_type_id=type_cash_out.id).aggregate(total_cash_out=Sum('amount'))['total_cash_out'] or 0
            prev_total_cash_in = trx_all.filter(trx_type_id=type_cash_in.id, create_date__lt=date.today().replace(day=1)).aggregate(prev_total_cash_in=Sum('amount'))['prev_total_cash_in'] or 0
            prev_total_cash_out = trx_all.filter(trx_type_id=type_cash_out.id, create_date__lt=date.today().replace(day=1)).aggregate(prev_total_cash_out=Sum('amount'))['prev_total_cash_out'] or 0
            opening_balance = (initial_balance + prev_total_cash_in - prev_total_cash_out) or 0
            net_balance = (opening_balance + total_cash_in - total_cash_out) or 0
            transactions = trx_this_month
        elif date_filter == 'last_month':
            # Filter transactions for the previous month
            trx_last_month_of_last_month = trx_all.filter(create_date__month=datetime.date.today().month - 2)
            total_cash_in = trx_last_month.filter(trx_type_id=type_cash_in.id).aggregate(total_cash_in=Sum('amount'))['total_cash_in'] or 0
            total_cash_out = trx_last_month.filter(trx_type_id=type_cash_out.id).aggregate(total_cash_out=Sum('amount'))['total_cash_out'] or 0
            prev_total_cash_in = trx_last_month_of_last_month.filter(trx_type_id=type_cash_in.id).aggregate(prev_total_cash_in=Sum('amount'))['prev_total_cash_in'] or 0
            prev_total_cash_out = trx_last_month_of_last_month.filter(trx_type_id=type_cash_out.id).aggregate(prev_total_cash_out=Sum('amount'))['prev_total_cash_out'] or 0
            opening_balance = (initial_balance + prev_total_cash_in - prev_total_cash_out) or 0
            net_balance = (opening_balance + total_cash_in - total_cash_out) or 0
            transactions = trx_last_month
        elif date_filter == 'single_day':
            # You need to implement the logic for filtering by a specific day
            pass
        elif date_filter == 'date_range':
            # You need to implement the logic for filtering by a date range
            pass
    else:
        date_filter = 'this_month'
        # Filter transactions for the current month
        total_cash_in = trx_this_month.filter(trx_type_id=type_cash_in.id).aggregate(total_cash_in=Sum('amount'))['total_cash_in'] or 0
        total_cash_out = trx_this_month.filter(trx_type_id=type_cash_out.id).aggregate(total_cash_out=Sum('amount'))['total_cash_out'] or 0
        prev_total_cash_in = trx_all.filter(trx_type_id=type_cash_in.id, create_date__lt=date.today().replace(day=1)).aggregate(prev_total_cash_in=Sum('amount'))['prev_total_cash_in'] or 0
        prev_total_cash_out = trx_all.filter(trx_type_id=type_cash_out.id, create_date__lt=date.today().replace(day=1)).aggregate(prev_total_cash_out=Sum('amount'))['prev_total_cash_out'] or 0
        opening_balance = (initial_balance + prev_total_cash_in - prev_total_cash_out) or 0
        net_balance = (opening_balance + total_cash_in - total_cash_out) or 0
        transactions = trx_this_month
    if trx_type_filter:
        # Apply transaction type filter based on the selected value
        transactions = trx_all.filter(trx_type_id=trx_type_filter)

    if category_filter:
        # Apply category filter based on the selected value
        transactions = trx_all.filter(category_id=category_filter)

    
    context = {
        'transactions': transactions,
        'trx_types': trx_types,
        'categories': categories,
        'type_cash_in': type_cash_in,
        'type_cash_out': type_cash_out,
        'net_balance': net_balance,
        'opening_balance': opening_balance,
        'total_cash_in': total_cash_in,
        'total_cash_out': total_cash_out,

        'date_filter': date_filter,
        'trx_type_filter': trx_type_filter,
        'category_filter': category_filter,
    }

    return render(request, 'cashbook/index.html', context)

    
# cash in transaction add
def cash_in(request):
    categories = Category.objects.filter(is_active=True).order_by("name")
    type_cash_in  = TrxType.objects.get(name='cash_in')
    type_cash_out = TrxType.objects.get(name='cash_out')
    
    acc_cash = Account.objects.get(name='cash')
    trx_all = Transaction.objects.order_by("-create_date")

    context = {
        'categories'    : categories
    }

    if request.method == 'POST':
        transaction   = Transaction()
        if request.POST['category'] != 'null':
            category_id = request.POST['category']
            category = get_object_or_404(Category, pk=category_id)
            transaction.category_id = category
        else:
            transaction.category_id = None

        transaction.account_id = Account.objects.get(name='cash')
        transaction.trx_type_id = type_cash_in
        transaction.amount          = request.POST['amount']
        transaction.remarks         = request.POST['remarks']
        transaction.create_date     = request.POST['create_date']
        transaction.save()

        # calculate net_balance
        total_cash_in = trx_all.filter(trx_type_id=type_cash_in.id).aggregate(total_cash_in=Sum('amount'))['total_cash_in'] or 0
        total_cash_out = trx_all.filter(trx_type_id=type_cash_out.id).aggregate(total_cash_out=Sum('amount'))['total_cash_out'] or 0

cashbook/templates/cashbook/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Cashbook</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    {% load static %}
</head>
<body>
    <div class="container">

        <div class="container">
            <div class="row justify-content-md-center">
              <div class="col-md-auto mt-4">
                <div class="card">
                    <div class="card-header">
                      
                      <!-- Navbar -->
                      <nav class="navbar navbar-expand-lg navbar-light bg-light">
                        <a href="{% url 'cashbook:index' %}" class="navbar-brand">
                          <h3 class="text-primary">My Cashbook</h3>
                        </a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                          <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarNav">
                          <ul class="navbar-nav">
                            <li class="nav-item {% if request.path == '/cashbook/' %}active{% endif %}">
                              <a class="nav-link" href="{% url 'cashbook:index' %}">Accounts <span class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item {% if request.path == '/cashbook/category/' %}active{% endif %}">
                              <a class="nav-link" href="{% url 'cashbook:manage_category' %}">Categories</a>
                            </li>
                            <li class="nav-item">
                              <a class="nav-link" href="#">Fund Transfer</a>
                            </li>
                            <li class="nav-item">
                              <a class="nav-link" href="#">Budget Manager</a>
                            </li>
                            <li class="nav-item {% if request.path == '/cashbook/contact/' %}active{% endif %}">
                              <a class="nav-link" href="{% url 'cashbook:contact' %}">About</a>
                            </li>
                            <li class="nav-item">
                              <a class="nav-link" href="#">Settings</a>
                            </li>
                          </ul>
                        </div>
                      </nav>

                    </div>
                    <div class="mb-3">
                        {% block content %}
                        {% endblock %}
                    </div>
                  </div>
              </div>
            </div>
        </div>

    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
</body>
</html>

cashbook/templates/cashbook/cash_in.html
<!-- cash_in.html -->

{% extends "cashbook/base.html" %}

{% block content %}
<div class="container">
    <!-- Back button -->
    <h4 class="mt-4"><a href="{% url 'cashbook:index' %}" type="button" class="mr-2"> <i class="fa fa-arrow-left"></i> </a> Add Cash In Transaction</h4>
  
    <form action="{% url 'cashbook:cash_in' %}" method="POST">
      {% csrf_token %}
      <div class="form-group">
        <label for="amount">Amount:</label>
        <input type="number" class="form-control" autofocus name="amount" required>
      </div>
  
      <div class="form-group">
        <label for="remarks">Remarks:</label>
        <input type="text" class="form-control" name="remarks">
      </div>
  
      
      <div class="form-group">
        <label for="category">Category:</label>
        <select class="form-control" name="category" required>
          <option value="null">--select category--</option>
          {% for category in categories %}
          <option value="{{ category.id }}">{{ category.name }}</option>
          {% endfor %}
        </select>
      </div>

      <div class="form-group">
        <label for="create_date">Date:</label>
        <input type="datetime-local" class="form-control" name="create_date" required>
      </div>
  
      <input type="submit" class="btn btn-primary" value="Submit">
    </form>
  </div>
{% endblock %}

cashbook/templates/cashbook/cash_out.html
<!-- cash_out.html -->

{% extends "cashbook/base.html" %}

{% block content %}
<div class="container">
    <h4 class="mt-4"><a href="{% url 'cashbook:index' %}" type="button" class="mr-2"> <i class="fa fa-arrow-left"></i> </a> Add Cash Out Transaction</h4>
  
    <form action="{% url 'cashbook:cash_out' %}" method="POST">
      {% csrf_token %}
      <div class="form-group">
        <label for="amount">Amount:</label>
        <input type="number" class="form-control" autofocus name="amount" required>
      </div>

      <div class="form-group">
        <label for="remarks">Remarks:</label>
        <input type="text" class="form-control" name="remarks">
      </div>
        
      <div class="form-group">
        <label for="category">Category:</label>
        <select class="form-control" name="category" required>
          <option value="null">--select category--</option>
          {% for category in categories %}
          <option value="{{ category.id }}">{{ category.name }}</option>
          {% endfor %}
        </select>
      </div>

      <div class="form-group">
        <label for="create_date">Date:</label>
        <input type="datetime-local" class="form-control" name="create_date" required>
      </div>
  
      <input type="submit" class="btn btn-primary" value="Submit">
    </form>
  </div>
{% endblock %}

cashbook/templates/cashbook/index.html
{% extends "cashbook/base.html" %}

{% block content %}
<!-- Search option -->
<div class="p-3">
    <div class="input-group mb-3">
        <input type="text" class="form-control" placeholder="Search by amount or remarks" aria-label="search" aria-describedby="basic-addon2">
        <div class="input-group-append">
          <button class="btn btn-outline-secondary" type="button"><i class="fa fa-search"></i></button>
        </div>
      </div>
</div>

<!-- Filter opthions -->
<div class="p-3" style="margin-top: -30px">
    <div class="row justify-content-md-center">
        <div class="col-4">
            <select class="form-control" name="date-filter" id="date-filter" required>
                <option value="" {% if date_filter == '' %}selected{% endif %}>Select Date</option>
                <option value="all-time" {% if date_filter == 'all-time' %}selected{% endif %}>All Time</option>
                <option value="today" {% if date_filter == 'today' %}selected{% endif %}>Today</option>
                <option value="yesterday" {% if date_filter == 'yesterday' %}selected{% endif %}>Yesterday</option>
                <option value="this_month" {% if date_filter == 'this_month' %}selected{% endif %}>This Month</option>
                <option value="last_month" {% if date_filter == 'last_month' %}selected{% endif %}>Last Month</option>
                <option value="single_day" {% if date_filter == 'single_day' %}selected{% endif %}>Single Day</option>
                <option value="date_range" {% if date_filter == 'date_range' %}selected{% endif %}>Date Range</option>
            </select>
        </div>
        <div class="col-4">
            <select class="form-control" name="trx-type" id="trx-type" required>
                <option value="">Trx Type</option>
                {% for type in trx_types %}
                <option value="{{ type.id }}" {% if trx_type_filter == type.id %}selected{% endif %}>{{ type.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="col-4">
            <select class="form-control" name="category" id="category" required>
                <option value="">Category</option>
                <option value="">No Category</option>
                {% for category in categories %}
                <option value="{{ category.id }}" {% if category_filter == category.id %}selected{% endif %}>{{ category.name }}</option>
                {% endfor %}
            </select>
        </div>
    </div>
</div>

<!-- Cash in and cash out option -->
  <div class="p-3" style="margin-top: -15px;">
    <div class="row">
        <div class="col-6">
            <a href="{% url 'cashbook:cash_in' %}" class="btn btn-success btn-block">Cash In</a>
        </div>
        <div class="col-6">
            <a href="{% url 'cashbook:cash_out' %}" class="btn btn-danger btn-block">Cash Out</a>
        </div>
      </div>
    </div>


    
    
    <!-- Calculated result for net balance, opening balance, total cash in, total cash out -->
    <div class="card">
        <div class="card-body">
            <ul class="list-group">
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Net Balance
                    <span class="badge badge-secondary badge-pill"><i class="fa-solid fa-bangladeshi-taka-sign"></i> {{ net_balance }}</span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Opening Balance
                    <span class="badge badge-primary badge-pill"><i class="fa-solid fa-bangladeshi-taka-sign"></i> {{ opening_balance }}</span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Total Cash In
                    <span class="badge badge-success badge-pill"><i class="fa-solid fa-bangladeshi-taka-sign"></i> {{ total_cash_in }}</span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Total Cash Out
                    <span class="badge badge-danger badge-pill"><i class="fa-solid fa-bangladeshi-taka-sign"></i> {{ total_cash_out }}</span>
                </li>
                <li class="list-group-item text-center">
                    <a href="#" class="text-decoration-none">View Reports <i class="fa fa-arrow-right"></i> </a>
                </li>
            </ul>
        </div>
    </div>

    <!-- Transaction list -->
    {% if transactions %}
    <div class="list-group">
        {% for trx in transactions %}
        <a href="{% url 'cashbook:edit_transaction' trx.id %}" class="list-group-item list-group-item-action flex-column align-items-start">
            <div class=" w-100">
                {% if trx.trx_type_id == type_cash_in %}
                <span class="badge badge-info mr-2">{{ trx.category_id.name }}</span>
                <span class="badge badge-secondary">Cash In</span>
                <span class="text-success float-right"><b><i class="fa-solid fa-bangladeshi-taka-sign"></i> {{ trx.amount }}</b></span>
                {% else %}
                <span class="badge badge-info mr-2">{{ trx.category_id.name }}</span>
                <span class="badge badge-secondary">Cash Out</span>
                <span class="text-danger float-right"><b><i class="fa-solid fa-bangladeshi-taka-sign"></i> {{ trx.amount }}</b></span>
                {% endif %}
            </div>
            <p class="mb-1">{{ trx.remarks }}</p>
            <small class="text-muted">{{ trx.create_date }}</small>
        </a>
        {% endfor %}
    </div>
    {% else %}
    <div class="card"">
        <div class="card-body">
            <ul class="list-group">
                <span>No Trx are available.</span>
            </ul>
        </div>
    </div>
        
    {% endif %}


<!-- JavaScript code -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
$(document).ready(function() {
    // Handle onchange event for filter options
    $('#date-filter, #trx-type, #category').on('change', function() {
        // Get selected values
        var dateFilter = $('#date-filter').val();
        var trxTypeFilter = $('#trx-type').val();
        var categoryFilter = $('#category').val();

        // Construct the URL with the selected filters
        var url = '/cashbook/?date-filter=' + dateFilter + '&trx-type=' + trxTypeFilter + '&category=' + categoryFilter;

        // Send the GET request
        window.location.href = url;
    });
});
</script>

{% endblock %}

cashbook/templates/cashbook/transaction_edit.html
{% extends "cashbook/base.html" %}

{% block content %}

<div class="container">
  <div class="d-flex justify-content-between mt-4">
    <!-- Back button -->
    <h4><a href="{% url 'cashbook:index' %}" type="button" class="mr-2"> <i class="fa fa-arrow-left"></i> </a> Edit Transaction</h4>
  
    <!-- Transaction delete form -->
    <form id="delete-form" action="{% url 'cashbook:delete_transaction' %}" method="POST">
      {% csrf_token %}
      <input type="hidden" name="transaction_id" value="{{ transaction.id }}">
      <div class="form-group">
        <input id="delete-button" type="submit" class="btn btn-outline-danger" value="Delete">
      </div>
    </form>
  </div>
    

    <form id="update-form" action="{% url 'cashbook:edit_transaction' transaction.id %}" method="POST">
      {% csrf_token %}
      <div class="form-group">
        <label for="amount">Amount:</label>
        <input type="number" class="form-control" name="amount" value="{{ transaction.amount }}" required>
      </div>
  
      <div class="form-group">
        <label for="remarks">Remarks:</label>
        <input type="text" class="form-control" name="remarks" value="{{ transaction.remarks }}">
      </div>
  

      <div class="form-group">
        <label for="category">Category: </label>
        <select class="form-control" name="category">  
          <option value="null" >--No category--</option>
          {% for category in categories %}
          <option value="{{ category.id }}" {% if category.id == transaction.category_id.id %}selected{% endif %}>{{ category.name }}</option>
          {% endfor %}
        </select>
      </div>
  
      <div class="form-group">
        <label for="trx_type">Transaction Type:</label>
        <select class="form-control" name="trx_type" required>
          {% for trx_type in trx_types %}
          <option value="{{ trx_type.id }}" {% if trx_type.id == transaction.trx_type_id.id %}selected{% endif %}>{{ trx_type.name }}</option>
          {% endfor %}
        </select>
      </div>

      <div class="form-group">
        <label for="create_date">Date:</label>
        <input type="datetime-local" class="form-control" name="create_date" value="{{ transaction.create_date|date:'Y-m-d\TH:i' }}" required>
      </div>
  
      <div class="form-group">
        <input type="submit" class="btn btn-primary" value="Update">
      </div>

    </form>
    
  </div>

  {% load static %}
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="{% static 'cashbook/scripts/delete-button.js' %}"></script>  

{% endblock %}