cashbook/urls.py
from django.urls import path
from . import views

app_name = "cashbook"
urlpatterns = [
    path("", views.index, name="index"),
    path('accounts/<str:acc_name>/', views.accounts_view, name='accounts_view'),

    path("transaction/cash_in", views.cash_in, name="cash_in"),
    path("transaction/cash_out", views.cash_out, name="cash_out"),
    path('transaction/edit/<int:transaction_id>/', views.edit_transaction, name='edit_transaction'),
    path('transaction/delete/', views.delete_transaction, name='delete_transaction'),
    
    path('contact/', views.contact_view, name='contact'),
    
    path('category/', views.manage_category, name='manage_category'),
    path('category/add', views.add_category, name='add_category'),
    path('category/edit/<int:category_id>', views.edit_category, name='edit_category'),
    path('category/delete/', views.delete_category, name='delete_category'),
]

cashmanager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("cashbook/", include("cashbook.urls"))
]

cashbook/models.py
from django.db import models
import datetime

class Category(models.Model):
    name = models.CharField(max_length=20)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name
    
class Account(models.Model):
    name            = models.CharField(max_length=20)
    initial_balance = models.FloatField(default=0)
    net_balance  = models.FloatField(default=0)
    last_updated = models.DateField(default=datetime.date.today)

    def __str__(self):
        return self.name

# define Transaction Type
class TrxType(models.Model):
    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name
    
class Transaction(models.Model):
    amount          = models.FloatField(blank=False, null=False)
    account_id      = models.ForeignKey(Account, on_delete=models.CASCADE)
    category_id     = models.ForeignKey(Category, null=True, on_delete=models.SET_NULL)
    trx_type_id     = models.ForeignKey(TrxType, on_delete=models.CASCADE)
    remarks         = models.TextField(blank=True)
    create_date     = models.DateTimeField("date created")

    def __str__(self):
        return f"Amount: {self.amount}, Remarks: {self.remarks}, Date: {self.create_date},"

cashbook/forms.py
# forms.py

from django import forms
from .models import Transaction, Category

class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ['amount', 'account_id', 'category_id', 'trx_type_id', 'remarks', 'create_date']

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']

cashbook/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .forms import TransactionForm, CategoryForm
from django.db.models import Q, Sum
from datetime import date, timedelta
from cashbook.models import Category, Account, Transaction, TrxType
from django.core.mail import send_mail
from django.conf import settings
import datetime
from dateutil import parser

def index(request):
    
    transactions = Transaction.objects.all()
    accounts = Account.objects.order_by("name")

    context = {
        'accounts'      : accounts,
        'transactions'  : transactions
    }
    return render(request, 'cashbook/accounts.html', context)

def accounts_view(request, acc_name):
    trx_types = TrxType.objects.all()
    categories = Category.objects.all()

    type_cash_in = TrxType.objects.get(name='cash_in')
    type_cash_out = TrxType.objects.get(name='cash_out')

    # Retrieve filter values
    date_filter = request.GET.get('date-filter')
    trx_type_filter = request.GET.get('trx-type')
    category_filter = request.GET.get('category')
    
    # Transaction by date
    trx_all = Transaction.objects.order_by("-create_date")
    trx_today = trx_all.filter(create_date__date=datetime.date.today())
    trx_yesterday = trx_all.filter(create_date__date=datetime.date.today() - datetime.timedelta(days=1))
    trx_this_month = trx_all.filter(create_date__month=datetime.date.today().month)
    trx_last_month = trx_all.filter(create_date__month=datetime.date.today().month - 1)

    # Calculate net balance, opening balance, total cash in, and total cash out
    acc_cash = Account.objects.get(name='cash')
    initial_balance = acc_cash.initial_balance
    opening_balance = 0
    total_cash_in = 0
    total_cash_out = 0
    net_balance = 0

    # Apply filters
    if date_filter:
        # Apply date filter based on the selected value
        
        if date_filter == 'today':
            # Filter transactions for today
            total_cash_in = trx_today.filter(trx_type_id=type_cash_in.id).aggregate(total_cash_in=Sum('amount'))['total_cash_in'] or 0
            total_cash_out = trx_today.filter(trx_type_id=type_cash_out.id).aggregate(total_cash_out=Sum('amount'))['total_cash_out'] or 0
            prev_total_cash_in = trx_all.filter(trx_type_id=type_cash_in.id, create_date__lt=datetime.date.today()).aggregate(prev_total_cash_in=Sum('amount'))['prev_total_cash_in'] or 0
            prev_total_cash_out = trx_all.filter(trx_type_id=type_cash_out.id, create_date__lt=datetime.date.today()).aggregate(prev_total_cash_out=Sum('amount'))['prev_total_cash_out'] or 0
            opening_balance = (initial_balance + prev_total_cash_in - prev_total_cash_out) or 0
            net_balance = (opening_balance + total_cash_in - total_cash_out) or 0
            transactions = trx_today
        elif date_filter == 'all-time':
            # Filter transactions for all-time
            total_cash_in = trx_all.filter(trx_type_id=type_cash_in.id).aggregate(total_cash_in=Sum('amount'))['total_cash_in'] or 0
            total_cash_out = trx_all.filter(trx_type_id=type_cash_out.id).aggregate(total_cash_out=Sum('amount'))['total_cash_out'] or 0
            opening_balance = initial_balance or 0
            net_balance = (opening_balance + total_cash_in - total_cash_out) or 0
            transactions = trx_all
        elif date_filter == 'yesterday':
            # Filter transactions for yesterday
            total_cash_in = trx_yesterday.filter(trx_type_id=type_cash_in.id).aggregate(total_cash_in=Sum('amount'))['total_cash_in'] or 0
            total_cash_out = trx_yesterday.filter(trx_type_id=type_cash_out.id).aggregate(total_cash_out=Sum('amount'))['total_cash_out'] or 0
            prev_total_cash_in = trx_all.filter(trx_type_id=type_cash_in.id, create_date__lt=datetime.date.today() - datetime.timedelta(days=1)).aggregate(prev_total_cash_in=Sum('amount'))['prev_total_cash_in'] or 0
            prev_total_cash_out = trx_all.filter(trx_type_id=type_cash_out.id, create_date__lt=datetime.date.today() - datetime.timedelta(days=1)).aggregate(prev_total_cash_out=Sum('amount'))['prev_total_cash_out'] or 0
            opening_balance = (initial_balance + prev_total_cash_in - prev_total_cash_out) or 0
            net_balance = (opening_balance + total_cash_in - total_cash_out) or 0
            transactions = trx_yesterday
        elif date_filter == 'this_month':
            # Filter transactions for the current month
            total_cash_in = trx_this_month.filter(trx_type_id=type_cash_in.id).aggregate(total_cash_in=Sum('amount'))['total_cash_in'] or 0
            total_cash_out = trx_this_month.filter(trx_type_id=type_cash_out.id).aggregate(total_cash_out=Sum('amount'))['total_cash_out'] or 0
            prev_total_cash_in = trx_all.filter(trx_type_id=type_cash_in.id, create_date__lt=date.today().replace(day=1)).aggregate(prev_total_cash_in=Sum('amount'))['prev_total_cash_in'] or 0
            prev_total_cash_out = trx_all.filter(trx_type_id=type_cash_out.id, create_date__lt=date.today().replace(day=1)).aggregate(prev_total_cash_out=Sum('amount'))['prev_total_cash_out'] or 0
            opening_balance = (initial_balance + prev_total_cash_in - prev_total_cash_out) or 0
            net_balance = (opening_balance + total_cash_in - total_cash_out) or 0
            transactions = trx_this_month
        elif date_filter == 'last_month':
            # Filter transactions for the previous month
            trx_last_month_of_last_month = trx_all.filter(create_date__month=datetime.date.today().month - 2)
            total_cash_in = trx_last_month.filter(trx_type_id=type_cash_in.id).aggregate(total_cash_in=Sum('amount'))['total_cash_in'] or 0
            total_cash_out = trx_last_month.filter(trx_type_id=type_cash_out.id).aggregate(total_cash_out=Sum('amount'))['total_cash_out'] or 0
            prev_total_cash_in = trx_last_month_of_last_month.filter(trx_type_id=type_cash_in.id).aggregate(prev_total_cash_in=Sum('amount'))['prev_total_cash_in'] or 0
            prev_total_cash_out = trx_last_month_of_last_month.filter(trx_type_id=type_cash_out.id).aggregate(prev_total_cash_out=Sum('amount'))['prev_total_cash_out'] or 0
            opening_balance = (initial_balance + prev_total_cash_in - prev_total_cash_out) or 0
            net_balance = (opening_balance + total_cash_in - total_cash_out) or 0
            transactions = trx_last_month
        elif date_filter == 'single_day':
            # You need to implement the logic for filtering by a specific day
            pass
        elif date_filter == 'date_range':
            # You need to implement the logic for filtering by a date range
            pass
    else:
        date_filter = 'this_month'
        # Filter transactions for the current month
        total_cash_in = trx_this_month.filter(trx_type_id=type_cash_in.id).aggregate(total_cash_in=Sum('amount'))['total_cash_in'] or 0
        total_cash_out = trx_this_month.filter(trx_type_id=type_cash_out.id).aggregate(total_cash_out=Sum('amount'))['total_cash_out'] or 0
        prev_total_cash_in = trx_all.filter(trx_type_id=type_cash_in.id, create_date__lt=date.today().replace(day=1)).aggregate(prev_total_cash_in=Sum('amount'))['prev_total_cash_in'] or 0
        prev_total_cash_out = trx_all.filter(trx_type_id=type_cash_out.id, create_date__lt=date.today().replace(day=1)).aggregate(prev_total_cash_out=Sum('amount'))['prev_total_cash_out'] or 0
        opening_balance = (initial_balance + prev_total_cash_in - prev_total_cash_out) or 0
        net_balance = (opening_balance + total_cash_in - total_cash_out) or 0
        transactions = trx_this_month
    if trx_type_filter:
        # Apply transaction type filter based on the selected value
        transactions = trx_all.filter(trx_type_id=trx_type_filter)

    if category_filter:
        # Apply category filter based on the selected value
        transactions = trx_all.filter(category_id=category_filter)

    
    context = {
        'transactions': transactions,
        'trx_types': trx_types,
        'categories': categories,
        'type_cash_in': type_cash_in,
        'type_cash_out': type_cash_out,
        'net_balance': net_balance,
        'opening_balance': opening_balance,
        'total_cash_in': total_cash_in,
        'total_cash_out': total_cash_out,

        'date_filter': date_filter,
        'trx_type_filter': trx_type_filter,
        'category_filter': category_filter,
    }

    return render(request, 'cashbook/index.html', context)

    
# cash in transaction add
def cash_in(request):
    categories = Category.objects.filter(is_active=True).order_by("name")
    type_cash_in  = TrxType.objects.get(name='cash_in')
    type_cash_out = TrxType.objects.get(name='cash_out')
    
    acc_cash = Account.objects.get(name='cash')
    trx_all = Transaction.objects.order_by("-create_date")

    context = {
        'categories'    : categories
    }

    if request.method == 'POST':
        transaction   = Transaction()
        if request.POST['category'] != 'null':
            category_id = request.POST['category']
            category = get_object_or_404(Category, pk=category_id)
            transaction.category_id = category
        else:
            transaction.category_id = None

        transaction.account_id = Account.objects.get(name='cash')
        transaction.trx_type_id = type_cash_in
        transaction.amount          = request.POST['amount']
        transaction.remarks         = request.POST['remarks']
        transaction.create_date     = request.POST['create_date']
        transaction.save()

        # calculate net_balance
        total_cash_in = trx_all.filter(trx_type_id=type_cash_in.id).aggregate(total_cash_in=Sum('amount'))['total_cash_in'] or 0
        total_cash_out = trx_all.filter(trx_type_id=type_cash_out.id).aggregate(total_cash_out=Sum('amount'))['total_cash_out'] or 0

cashbook/templates/cashbook/category/add_category.html
{% extends "cashbook/base.html" %}

{% block content %}
<div class="card-body">
    
    <div class="d-flex justify-content-between mt-4">
        <!-- Back button -->
        <h4 ><a href="{% url 'cashbook:manage_category' %}" type="button" class="mr-2"> <i class="fa fa-arrow-left"></i> </a> Add Category</h4>
      
    </div>

    <form action="{% url 'cashbook:add_category' %}" class="mt-3" method="POST">
        {% csrf_token %}
        <div class="form-group">
          <input type="text" class="form-control" id="name" name="name" placeholder="Enter category name" autofocus required>
        </div>
        <div class="form-check">
          <input class="form-check-input" type="checkbox" name="is_active" id="is_active" checked>
          <label class="form-check-label" for="is_active">
              Active
          </label>
        </div>
        <button type="submit" class="btn btn-primary mt-3">Submit</button>
      </form>


</div>
{% endblock %}

cashbook/templates/cashbook/category/edit_category.html
{% extends "cashbook/base.html" %}

{% block content %}
<div class="card-body">
    
    <div class="d-flex justify-content-between mt-4">
        <!-- Back button -->
        <h4 ><a href="{% url 'cashbook:manage_category' %}" type="button" class="mr-2"> <i class="fa fa-arrow-left"></i> </a> Edit Category</h4>

    </div>

    <form action="{% url 'cashbook:edit_category' category.id %}" class="mt-3" method="POST">
        {% csrf_token %}
        <div class="form-group">
          
          <input type="text" class="form-control" id="name" name="name" placeholder="Enter category name" autofocus value="{{ category.name }}" required>
          
        </div>
        <div class="form-check">
          <input class="form-check-input" type="checkbox" name="is_active" id="is_active" {% if category.is_active %}checked{% endif %}>
          <label class="form-check-label" for="is_active">
              Active
          </label>
        </div>
        <button type="submit" class="btn btn-primary mt-3">Update</button>
      </form>


</div>
{% endblock %}

cashbook/templates/cashbook/category/manage_category.html
{% extends "cashbook/base.html" %}

{% block content %}
<div class="card-body">
    
    <div class="d-flex justify-content-between mt-4">
        <!-- Back button -->
        <h4 ><a href="{% url 'cashbook:index' %}" type="button" class="mr-2"> <i class="fa fa-arrow-left"></i> </a> Manage Category</h4>
      
        <a href="{% url 'cashbook:add_category' %}" class="btn btn-outline-primary">Add Category</a>

    </div>

<!-- Action Button -->
    <form class="form-inline mt-3">
        <label class="my-1 mr-2" for="inlineFormCustomSelectPref">Action: </label>
        <select class="custom-select my-1 mr-sm-2" id="inlineFormCustomSelectPref">
          <option selected>--Choose--</option>
          <option value="delete">Delete</option>
          <option value="active">Active</option>
          <option value="deactive">Deactive</option>
        </select>
        <button type="submit" class="btn btn-secondary my-1 mr-2">Go</button>
        <span>0 of {{ total_categories }} selected</span>
      
      </form>


      <!-- List Category -->
    <ul class="list-group mt-2">
        <li class="list-group-item form-check form-check-inline">
            <div class="form-check form-check-inline">
                <input class="form-check-input mr-4" type="checkbox" id="inlineCheckbox1" value="option1">
                <label class="form-check-label text-uppercase" for="inlineCheckbox1">Category</label>
            </div>
        </li>
        {% for category in categories %}
        <li class="list-group-item ">
            <div class="form-check form-check-inline">
                <input class="form-check-input mr-4" type="checkbox" id="inlineCheckbox1" value="option1">
                <label class="form-check-label" for="inlineCheckbox1">
                    <a href="{% url 'cashbook:edit_category' category.id %}" class="text-decoration-none">{{ category.name }}</a>
                </label>
            </div>
            <a href="{% url 'cashbook:edit_category' category.id %}" class="text-decoration-none   d-inline">
                {% if category.is_active %}
                <i class=" text-success fa-regular fa-eye"></i>
                {% else %}
                <i class="text-danger fa-regular fa-eye-slash"></i>
                {% endif %}
            </a> 
            <a href="{% url 'cashbook:edit_category' category.id %}" class="text-decoration-none  float-right d-inline">
                <i class="fa-regular fa-pen-to-square"></i>
            </a> 
            <form action="{% url 'cashbook:delete_category' %}" method="post" class="float-right d-inline pr-4 delete-form">
                {% csrf_token %}
                <input type="hidden" name="category_id" value="{{ category.id }}">
                <button type="submit" class="btn btn-danger btn-sm delete-button"><i class="fa fa-trash"></i></button>
            </form>

        </li>
        
        {% endfor %}
        <li class="list-group-item"><span>{{ total_categories }} Categories </span></li>
      </ul>
</div>


    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function() {
        // Click event handler for the Delete button
        $(".delete-button").click(function(e) {
            e.preventDefault(); // Prevent the default form submission

            if (window.confirm("Are you sure you want to delete this?")) {
            $(this).closest(".delete-form").submit(); // Submit the Delete form related to the clicked button
            }
        });
        });

    </script>

{% endblock %}